variables:
  base_folder: "/home/julienb/Documents/database_scripts"
  this_run_config: "song_annotation"


runs: 
  # - 
  #   script: "**/create_train_song.ipynb"
  #   imports: ["**/config_adapter.py", "**/helper.py"]
  #   environment: dbscripts

  #   script_params:
  #     config_path: '/home/julienb/Documents/database_scripts/templates/create_train_song.yaml'
  #     variables:
  #       koe_link: 'https://koe.io.ac.nz/user_data/history/aleblois-2024-10-21_08-57-17_UTC.zip'
  #   run_folder: '{base_folder}/runs/{this_run_config}/create_train_song'

  - 
    script: "**/das_train.ipynb"
    id: 'das_train'
    imports: ["**/config_adapter.py", "**/helper.py"]
    environment: das

    script_params:
      config_path: '/home/julienb/Documents/database_scripts/templates/das_train.yaml'
      dataset_location: '{base_folder}/runs/{this_run_config}/create_train_song/das_train_dataset.npy'
    run_folder: '{base_folder}/runs/{this_run_config}/das_train'

  - 
    script: "**/das_predict.ipynb"
    imports: ["**/config_adapter.py", "**/helper.py"]
    requires_sucess: ['das_train']
    environment: das

    script_params:
      config_path: '/home/julienb/Documents/database_scripts/templates/das_predict.yaml'
      song_path: '/home/julienb/Documents/rtxi_test_sound/processed_data/Templates_test_Hania.wav'
      model_path: '{base_folder}/runs/{this_run_config}/das_train/model'
    run_folder: '{base_folder}/runs/{this_run_config}/das_predict1'

run_summary_folder: '{base_folder}/runs/{this_run_config}/summary'