context:
  variables:
    base_folder: "/home/julienb/Documents/database_scripts"
    this_run_config: "test_runconfig_v1"

  tables:
    # - name: test
    #   method: csv_loader
    #   method_params:
    #     file:
    #     sep:
    #     names: auto
    - name: all_dat_files
      method: file_scan
      method_params:
        column_name: dat_file
        base_folder: '{base_folder}'
        pattern: '(?P<dat_folder>.*)/(?P<dat_stem>[^/]*)\.dat'
    - name: session_data
      method: add_columns
      method_params:
        initial_table: all_dat_files
        new_columns:
          - name: task_file
            method: search_upwards
            method_params:
              search_from_expr: '{dat_folder}' 
              max_folder: '{base_folder}'
              pattern: '(?P<task_folder>.*)/(?P<task_stem>[^/]*)\.xls'
              num_to_find: 1
              on_invalid_numtofind: "raise"
          - name: config_file
            method: search_upwards
            method_params:
              search_from_expr: '{dat_folder}' 
              max_folder: '{base_folder}'
              pattern: '(?P<config_folder>.*)/(?P<config_stem>poly\w*config)\.yaml'
              num_to_find: 1
              on_invalid_numtofind: "raise"

    # - name: 'channels'
    #   method: auto_generated
    #   method_params:
    #     id: "channels"



runs: 
  - duplicate_over:
      table_name: session_data
      variables: ["dat_file", "task_file", "config_file"]

    script: "polydat_file_to_events2.ipynb"
    imports: ["events_methods.py", "helper.py"]
    environment: dbscripts

    script_params:
      dat_path: '/home/julienb/Documents/database_scripts/analysis_test_data/poly_dat_files/Rats/Luisa/Rat101_0729_opto_01/Rat101_0729_opto_01.dat'
      task_path: '/home/julienb/Documents/database_scripts/analysis_test_data/poly_dat_files/Rats/Luisa/Rat101_0729_opto_01.xls'
      config_path: '/home/julienb/Documents/database_scripts/templates/poly_rat_model.yaml'
      dest_path: 'events.tsv'
    run_folder: '{base_folder}/runs/{this_run_config}/poly'
    
run_summary_folder: '{base_folder}/runs/{this_run_config}/summary'