- action: declare_var
  name: 'base_folder'
  value: '/home/julienb/Documents/database_scripts'

- action: declare_var
  name: 'this_run_config'
  value: 'song_annotation2'

- action: declare_table
  name: 'test'
  table: 
    method: "from_rows"
    method_params:
      column_names: ["x", "y"] 
      data: [[1, 1]]

- action: declare_run
  script: "**/create_train_song.ipynb"
  id: "create_train_song"
  imports: ["**/config_adapter.py", "**/helper.py"]
  environment: dbscripts

  script_params:
    config_path: '/home/julienb/Documents/database_scripts/templates/create_train_song.yaml'
    variables:
      koe_link: 'https://koe.io.ac.nz/user_data/history/aleblois-2024-10-21_08-57-17_UTC.zip'
  run_folder: '{base_folder}/runs/{this_run_config}/create_train_song'

- action: declare_run
  script: "**/das_predict.ipynb"
  id: "das_predict"
  imports: ["**/config_adapter.py", "**/helper.py"]
  depends_on: ['das_train']
  environment: das

  script_params:
    config_path: '/home/julienb/Documents/database_scripts/templates/das_predict.yaml'
    song_path: '/home/julienb/Documents/rtxi_test_sound/processed_data/Templates_test_Hania.wav'
    model_path: '{base_folder}/runs/{this_run_config}/das_train/model'
  run_folder: '{base_folder}/runs/{this_run_config}/das_predict2'

- action: declare_run
  script: "**/das_train.ipynb"
  id: 'das_train'
  imports: ["**/config_adapter.py", "**/helper.py"]
  depends_on: ["create_train_song"]
  environment: das

  script_params:
    config_path: '/home/julienb/Documents/database_scripts/templates/das_train.yaml'
    dataset_location: '{base_folder}/runs/{this_run_config}/create_train_song/das_train_dataset.npy'
  run_folder: '{base_folder}/runs/{this_run_config}/das_train'

- action: display_run
- action: run
